
name: .nojekyll creator

on:
  push:
    branches: [gh-pages]
  pull_request:
    branches: [gh-pages]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
     

      - run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/portableCoder/Lofi-Doro.git
      - run: git checkout gh-pages
      - run: git pull origin gh-pages
      - run: touch .nojekyll
      - run: git add .
      - run: git commit -m "add .nojekyll"
      - run: git push origin gh-pages
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
